### PR TITLE
Release application FIlmary 

### PR DESCRIPTION
**Pull request by DzmitryBandarenka**
1. Asp .Net Core , MVC, Identtity Framework, HTML, CSS
2.
Безымянный
3. 20.12.2020

### CODE REVIEW

**Comment by MikhailMasny** [comment]
Do you need TestApiApp project in solution?

**Comment by MikhailMasny** [comment]
I would put the work with the external API in a separate assembly (project via class library)

**Review by MikhailMasny — APPROVED** [review]
Ok

**Comment by DzmitryBandarenka** [comment]
No.  Forgot to delete this project(

**Review by MikhailMasny — APPROVED** [review]
Great job! 💯

**Pull request merged**
